modLoader="javafml"
loaderVersion="[4,)"
license="All Rights Reserved"

[[mods]]
modId="skyrain"
version="1.0.0"
displayName="SkyRain"
authors="Sebas"
description='''
A simple NeoForge test mod that adds Monolith and Quicksilver, with reversible crafting recipes.
'''

[[dependencies.skyrain]]
modId="neoforge"
type="required"
versionRange="[21.0.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.skyrain]]
modId="minecraft"
type="required"
versionRange="[1.21,1.22)"
ordering="NONE"
side="BOTH"
